<?php

namespace Kamil\AddressBookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllBySurname()
    {
        $data = $this->getEntityManager()->createQuery('Select user From KamilAddressBookBundle:User user Order By user.surname ASC')
                ->getResult();
        return $data;
    }
}
